### ISSUE TITLE
[Redoc] full_node.html is missing

### ISSUE THREAD

**Issue by dkackman** [dkackman/chia-api#6]
When generating the redocly site full_node.yaml generates the following error.

```
Created build\full_node.yaml from src/full_node.yaml
Prerendering docs
Error: Invalid reference token: properties
    at Function.get (C:\Users\dkack\src\github\dkackman\chia-api\node_modules\redoc-cli\node_modules\openapi-sampler\dist\openapi-sampler.js:79:19)
    at traverse (C:\Users\dkack\src\github\dkackman\chia-api\node_modules\redoc-cli\node_modules\openapi-sampler\dist\openapi-sampler.js:941:43)
    at C:\Users\dkack\src\github\dkackman\chia-api\node_modules\redoc-cli\node_modules\openapi-sampler\dist\openapi-sampler.js:646:43
    at Array.forEach (<anonymous>)
    at sampleObject (C:\Users\dkack\src\github\dkackman\chia-api\node_modules\redoc-cli\node_modules\openapi-sampler\dist\openapi-sampler.js:640:36)
    at traverse (C:\Users\dkack\src\github\dkackman\chia-api\node_modules\redoc-cli\node_modules\openapi-sampler\dist\openapi-sampler.js:1017:17)
    at C:\Users\dkack\src\github\dkackman\chia-api\node_modules\redoc-cli\node_modules\openapi-sampler\dist\openapi-sampler.js:646:43
    at Array.forEach (<anonymous>)
    at sampleObject (C:\Users\dkack\src\github\dkackman\chia-api\node_modules\redoc-cli\node_modules\openapi-sampler\dist\openapi-sampler.js:640:36)
    at traverse (C:\Users\dkack\src\github\dkackman\chia-api\node_modules\redoc-cli\node_modules\openapi-sampler\dist\openapi-sampler.js:1017:17)
```

**Comment by dkackman** [comment]
It might be a bug in redocly-cli. (https://github.com/Redocly/redoc/issues/452#issuecomment-1058812985)
